name: Autocloser
on: [issues, pull_request]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues that did not follow issue template
      uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-close-message: "
          @${issue.user.login} this issue was automatically closed because the package
          is no longer maintained.
          If you need help, refer to the package documentation first;
          then, address remaining doubts to public forums like StackOverflow,
          where other users could eventually provide useful ticks.
          "
        issue-pattern: ".*do not autoclose this issue.*"
